version: '3'

services:

    postgres:
        container_name: dev-postgres
        image: postgres:12.0-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=password
            - POSTGRES_DB=goblog