version: '3'

services:

    postgres:
        container_name: goblog_postgres_dev
        image: postgres:12.0-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASS=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - goblog_db:/var/lib/postgresql/data/

volumes:
    goblog_db: