version: '3'

services:

    goblog:
        container_name: goblog_api_dev
        image: effprime/goblog-api:dev-1.0
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            - DEBUG=1